# Generated by Django 5.1.1 on 2026-06-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("subject", models.CharField(max_length=70)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Interns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        default="Software Engineering Intern", max_length=100
                    ),
                ),
                ("bio", models.TextField()),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True, help_text="Direct link to a premium profile image"
                    ),
                ),
                ("github_link", models.URLField(blank=True)),
                ("linkedin_link", models.URLField(blank=True)),
                ("joined_date", models.DateField()),
            ],
        ),
    ]
